---
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=${PLEX_PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ../data/plex/config:/config
      - ${TELEVISION_PATH}:/mnt/Television
      - ${MOVIES_PATH}:/mnt/Movies
    restart: unless-stopped